---
name: docker_push

on:
  push:
    tags:
      - '*'
jobs:
  docker_push:
    runs-on: ubuntu-latest
    environment: docker-builder
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          mkdir ~/.docker/ -p
          echo '${{ secrets.DOCKER_CONFIG_JSON }}' > ~/.docker/config.json
      - run: test -z "$GITHUB_REF_NAME" || docker build . -t "nett00n/traefik-certs-exporter:$GITHUB_REF_NAME"
      - run: test -z "$GITHUB_REF_NAME" || docker push "nett00n/traefik-certs-exporter:$GITHUB_REF_NAME"
      - run: test -z "$GITHUB_SHA" || docker build . -t "nett00n/traefik-certs-exporter:$GITHUB_SHA"
      - run: test -z "$GITHUB_SHA" || docker push "nett00n/traefik-certs-exporter:$GITHUB_SHA"
