---
name: "Push to Dockerhub"

on:
  push:
    tags:
      - '*'
    branches:
      - "main"
jobs:
  docker_push:
    runs-on: ubuntu-latest
    environment: docker-builder
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          mkdir ~/.docker/ -p
          echo '${{ secrets.DOCKER_CONFIG_JSON }}' > ~/.docker/config.json
      - run: |
          docker build . -t "nett00n/traefik-certs-exporter:${{ github.ref_name }}"
          docker push "nett00n/traefik-certs-exporter:${{ github.ref_name }}"
