name: Upload Go test results

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.19

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          ls -lah
          pwd
      # - name: Upload Go binaries
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: traefik-certs-exporter
      #     path: ${${GOROOT}}/traefik-certs-exporter
