---
name: "Build linux binaries"

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          go-version: 1.19
      - run: go install github.com/mgechev/revive@v1.2.4
      - run: go build traefik-certs-exporter.go
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: traefik-certs-exporter
          asset_name: traefik-certs-exporter_v${{ github.GITHUB_REF_NAME }}
          asset_content_type: application
