---
name: revive linters

on:
  push:

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: tar cvf traefik-certs-exporter.tar ./
      - uses: actions/upload-artifact@v3
        with:
          name: sources
          path: traefik-certs-exporter.tar
      - run: go install github.com/mgechev/revive@v1.2.4
      - run: go build traefik-certs-exporter.go
      - uses: actions/upload-artifact@v3
        with:
          name: binary_linux
          path: traefik-certs-exporter
