name: "Build linux binaries"

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  linux_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19]
        platform: [amd64, arm64, arm]

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install revive
        run: go install github.com/mgechev/revive@v1.2.4

      - name: Build binaries
        run: |
          GOARCH=${{ matrix.platform }}
          if [ "$GOARCH" == "arm" ]; then GOARM=6; else GOARM=7; fi
          GOOS=linux GOARCH=$GOARCH GOARM=$GOARM go build -o traefik-certs-exporter_${{ matrix.platform }} traefik-certs-exporter.go

      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: traefik-certs-exporter_${{ matrix.platform }}
          asset_name: traefik-certs-exporter_${{ matrix.platform }}_${{ github.ref_name }}
          asset_content_type: application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
